version: '3'

services:

  backend:
    container_name: backend
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    networks:
      - config_some-net

networks:
  config_some-net:
    external: true
