version: '3'

services:

  backend:
    container_name: backend
    build:
      context: ./demo
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    networks:
      - default

networks:
  default:
    external:
      name: scoring_default
