version: '3'

services:

  backend:
    container_name: backend
    build:
      context: ./demo
      dockerfile: Dockerfile
    depends_on:
      - config
    ports:
      - "8085:8080"
    networks:
      mynet:

  config:
    container_name: config
    build:
      context: ./configserver
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    links:
      mynet:

networks:
  mynet:
    driver: bridge
