version: '3'

services:

  backend:
    container_name: backend
    build:
      context: ./demo
      dockerfile: Dockerfile
    depends_on:
      - config
    ports:
      - "8085:8080"
    networks:
      mynet:

networks:
  mynet:
    driver: bridge
